### ISSUE TITLE
Motivation for splitting miniz.c into multiple files

### ISSUE THREAD

**Issue by gpakosz** [uroni/miniz#2]
Hello,

In https://github.com/richgel999/miniz/pull/57 you mention your fork is going to be the next miniz release. May I ask you what's the motivation behind splitting `miniz.c` into multiple files? Being able to drop `miniz.c` into any build was really confortable. Not to mention `miniz.c` is likely an implementation detail of a bigger system that maybe already abstracts files, archives, VFS etc...

**Comment by uroni** [comment]
The releases are single miniz.c/miniz.h ( see https://github.com/uroni/miniz/releases ) built by amalgamate.sh . This mirrors how SQLite does it.
